const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto').webcrypto;
const source=fs.readFileSync('templates/dashboard.html','utf8');
let nodes={},timerCallback,timerCleared=0;
function element(){return {textContent:'',innerHTML:'',children:[],appendChild(child){this.children.push(child);},setAttribute(){},addEventListener(type,fn){this.listener=fn;},querySelectorAll(){return [];}};}
const document={getElementById:id=>nodes[id]||(nodes[id]=element()),createElement:element};
const storage=new Map();const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
const context={document,crypto,TextEncoder,localStorage,AbortController,setTimeout:fn=>(timerCallback=fn,1),clearTimeout:()=>timerCleared++,state:{lang:'en',workers:[]},fmtMoney:n=>'₹'+Number(n),colorFor:()=> '#123',initials:name=>String(name).slice(0,2),t:k=>k,skillIcon:()=>'',catColors:()=>['#123','#fff'],nav:()=>{},openWorkerProfileScreen:()=>{},openWorkerListScreen:()=>{}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('  function api('),source.indexOf('  function uiFormatLocale('))+source.slice(source.indexOf('  function hirerMessageText('),source.indexOf('\n',source.indexOf('  function hirerMessageText('))),context);
vm.runInContext(source.slice(source.indexOf('  function renderCategories(skills)'),source.indexOf('  document.getElementById("fCity").addEventListener')),context);
const attack='\"><img src=x onerror="alert(1)">&';
context.state.workers=[{id:1,name:attack,skill:attack,city:attack,rating:5}];context.renderFeatured();assert.doesNotMatch(nodes.featuredScroll.innerHTML,/<img/);assert.match(nodes.featuredScroll.innerHTML,/&lt;img/);
context.renderCategories([attack]);assert.doesNotMatch(nodes.categoryGrid.innerHTML,/<img/);assert.match(nodes.categoryGrid.innerHTML,/&quot;/);
const bookingStart=source.indexOf('        stackBody.innerHTML =',source.indexOf('  function openBookingDetailsScreen('));
const bookingEnd=source.indexOf('\n        if(b.booking_type ===',bookingStart);
context.stackBody=element();context.b={id:1,worker_id:1,worker_name:attack,worker_skill:attack,worker_rating:5,start_date:'2026-10-08',start_time:'10:00',hours:2,status:'completed',payment_status:'paid',payment_method:'cash',total_amount:200,paid_amount:200,address:attack,special_instructions:attack,diagnosis_notes:attack};
context.guide={title:'Completed',note:'Paid'};context.hirerBookingProgress=()=>'';context.bookingStatusClass=()=> 'completed';context.statusLabel=s=>s;
vm.runInContext(source.slice(bookingStart,bookingEnd),context);assert.doesNotMatch(context.stackBody.innerHTML,/<img/);assert.match(context.stackBody.innerHTML,/&lt;img/);assert.match(context.stackBody.innerHTML,/refReceipt/);
const profileStart=source.indexOf('      stackBody.innerHTML =',source.indexOf('  function openWorkerProfileScreen('));const profileEnd=source.indexOf('\n      stackBody.querySelector("#wpBack")',profileStart);
context.w={id:1,name:attack,city:attack,about:attack,skill:attack,rating:5};context.isFav=false;context.isVerified=false;context.tags=[attack];context.derivedHourly=100;
vm.runInContext(source.slice(profileStart,profileEnd),context);assert.doesNotMatch(context.stackBody.innerHTML,/<img/);
const formStart=source.indexOf("      stackBody.innerHTML='<div class=\"ref-worker-mini",source.indexOf('  function openBookingScreen('));const formEnd=source.indexOf("\n      stackBody.querySelectorAll('[data-date]')",formStart);
Object.assign(context,{hourly:100,hrs:2,estimate:200,isDiagnosis:false,selectedType:'regular',selectedDate:'2026-10-08',today:'2026-10-08',tomorrowDate:'2026-10-09',slotsLoading:false,availableSlots:[],slotError:attack,selectedTime:'10:00',selectedEnd:'12:00',bookingAddress:attack,bookingNotes:'</textarea>'+attack,bookingLat:null,bookingLng:null,selectedPayment:'cash',time24:v=>v});
vm.runInContext(source.slice(formStart,formEnd),context);assert.doesNotMatch(context.stackBody.innerHTML,/<img/);assert.match(context.stackBody.innerHTML,/&lt;\/textarea&gt;/);
const errorBox=element();let retried=false;context.showHirerLoadError(errorBox,attack,()=>retried=true);assert.equal(errorBox.children[0].textContent,attack);assert.equal(errorBox.children[0].innerHTML,'');errorBox.children[1].listener();assert.equal(retried,true);
(async()=>{
 const realApi=context.api;
 context.stackRevision=0;context.openStack=(_,title,render)=>{context.stackRevision++;render();};context.hcui=k=>k;
 vm.runInContext(source.slice(source.indexOf('  function openBookingDetailsScreen('),source.indexOf('  // ---------------- floating chat popup',source.indexOf('  function openBookingDetailsScreen('))),context);
 context.api=async()=>({ok:false,data:{error:attack}});context.stackBody=element();context.openBookingDetailsScreen(1);await Promise.resolve();
 assert.equal(context.stackBody.children[0].textContent,attack);assert.equal(context.stackBody.children[1].textContent,'Retry');
 let resolve;context.api=()=>new Promise(r=>resolve=r);context.stackBody=element();context.openBookingDetailsScreen(1);context.stackRevision++;resolve({ok:true,data:{}});await Promise.resolve();assert.equal(context.stackBody.children.length,0);
 vm.runInContext(source.slice(source.indexOf('  function openNotificationsScreen('),source.indexOf('  document.getElementById("notifBtn")',source.indexOf('  function openNotificationsScreen('))),context);
 let notificationCalls=0;context.api=async()=>{notificationCalls++;return {ok:false,data:{error:'Unavailable'}};};context.stackBody=element();context.openNotificationsScreen();await Promise.resolve();assert.equal(notificationCalls,1);assert.match(context.stackBody.children[0].textContent,/Unavailable/);
 vm.runInContext(source.slice(source.indexOf('  var pendingBookingKeys='),source.indexOf('  function showPayStep(')),context);
 const msg=element(),button={dataset:{},disabled:false,textContent:''};context.stackBody={querySelector:id=>id==='#refProceed'?button:msg};context.api=async()=>({ok:false,data:{error:attack}});
 const bookingTask=context.createReferenceBooking({id:1},{});assert.equal(button.disabled,true);await bookingTask;assert.equal(button.disabled,false);assert.doesNotMatch(msg.innerHTML,/<img/);
 context.api=realApi;
 let count=0;context.fetch=async()=>{count++;return {ok:true,status:200,json:async()=>({id:1})};};
 let result=await context.api('/api/bookings');assert.equal(result.ok,true);assert.equal(result.status,200);assert.equal(count,1);
 context.fetch=async()=>({ok:false,status:502,json:async()=>{throw Error('HTML response');}});result=await context.api('/api/bookings');assert.equal(result.ok,false);assert.equal(result.status,502);assert.match(result.data.error,/could not be read/);
 context.fetch=async()=>{throw Error('Network down');};result=await context.api('/api/bookings');assert.equal(result.status,0);assert.match(result.data.error,/Connection failed/);
 context.fetch=async()=>({ok:true,status:200,json:async()=>null});assert.equal((await context.api('/api/bookings')).ok,false);
 context.fetch=(_,opts)=>new Promise((resolve,reject)=>opts.signal.addEventListener('abort',()=>{const error=new Error();error.name='AbortError';reject(error);}));const pending=context.api('/api/bookings');timerCallback();result=await pending;assert.match(result.data.error,/timed out/);assert.equal(timerCleared,5);
 console.log('Hirer rendering, retry and API failure tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
