const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('templates/worker.html','utf8');
const guidance=source.slice(source.indexOf('  function detailNextAction('),source.indexOf('  function canVerifyWorkerCash('));
const functions=source.slice(source.indexOf('  function canVerifyWorkerCash('),source.indexOf('  function openJobDetail('));
const escaping=source.slice(source.indexOf('  function earningsText('),source.indexOf('  function paintEarnings('));
let calls=[],refreshes=0,response={ok:true,data:{cash_verified:true,payment_status:'paid'}};
const context={state:{lang:'en'},STATUS_LABELS_BY_LANG:{en:{completed:'Completed',cancelled:'Cancelled',checked_in:'Checked in',requested:'New request'}},NEXT_ACTION_BY_LANG:{en:{}},wguide:k=>k,wresponse:k=>k,fmtMoney:n=>'₹'+n,fmtDate:d=>d,jobTitle:b=>b.service_name||'Service job',window:{alert:()=>{}},loadBookings:()=>refreshes++,api:(url,options)=>{calls.push({url,options});return Promise.resolve(response);}};
vm.createContext(context);vm.runInContext(guidance+functions+escaping,context);
const job={id:12,status:'completed',payment_method:'cash',payment_status:'cash_pending',paid_amount:0,total_amount:200,start_date:'2026-10-08',start_time:'10:00',end_time:'12:00',special_instructions:'Fix the tap\nCall before arrival'};
function render(changes={}){let b={...job,...changes};return context.workerJobDetailHtml(b,context.detailNextAction(b));}
assert.match(render(),/detailCashForm/);
assert.match(render(),/I received the full cash amount/);
assert.match(render(),/Fix the tap\nCall before arrival/);
assert.match(render(),/India \(IST\)/);
for(const changes of [{payment_status:'paid',paid_amount:200},{payment_method:'online'},{status:'cancelled'},{status:'checked_in'},{status:'requested'}])assert.doesNotMatch(render(changes),/detailCashForm/);
assert.match(render({payment_status:'paid',paid_amount:200}),/data-detail-receipt/);
assert.doesNotMatch(render({payment_status:'paid',paid_amount:200}),/data-detail-next/);
assert.match(render({booking_type:'diagnosis'}),/detailCashForm/);
assert.match(render({request_expired_at:'2026-10-08',status:'cancelled'}),/Request expired/);
const attack='<img src=x onerror="alert(1)">';
const html=render({special_instructions:attack,hirer_name:attack,address:attack,service_name:attack,description:'WRONG DESCRIPTION'});
assert.doesNotMatch(html,/<img/);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/WRONG DESCRIPTION/);
assert.match(render({special_instructions:''}),/No special instructions/);
assert.doesNotMatch(render({id:'bad" onclick="x'}),/onclick/);
(async()=>{
 const input={value:'abcdef',focus(){}},button={dataset:{},disabled:false,textContent:''},feedback={textContent:''},received={checked:true};
 await context.verifyWorkerCashPayment(12,input,button,feedback,received);assert.equal(calls.length,0);assert.match(feedback.textContent,/6-digit/);
 input.value='123456';received.checked=false;await context.verifyWorkerCashPayment(12,input,button,feedback,received);assert.equal(calls.length,0);
 received.checked=true;
 let resolve;context.api=(url,options)=>{calls.push({url,options});return new Promise(r=>resolve=r);};
 const pending=context.verifyWorkerCashPayment(12,input,button,feedback,received);
 await context.verifyWorkerCashPayment(12,input,button,feedback,received);assert.equal(calls.length,1);assert.equal(button.disabled,true);
 assert.equal(calls[0].url,'/api/worker/bookings/12/verify-cash-otp');assert.equal(JSON.parse(calls[0].options.body).otp,'123456');
 resolve({ok:false,data:{error:'OTP expired — ask hirer for a new OTP'}});await pending;
 assert.match(feedback.textContent,/OTP expired/);assert.equal(button.disabled,false);assert.equal(refreshes,0);
 context.api=()=>Promise.resolve({ok:true,data:{cash_verified:true,payment_status:'paid'}});
 await context.verifyWorkerCashPayment(12,input,button,feedback,received);assert.equal(refreshes,1);assert.equal(input.value,'');
 input.value='123456';context.api=()=>Promise.reject(new Error('Network unavailable'));
 await context.verifyWorkerCashPayment(12,input,button,feedback,received);assert.match(feedback.textContent,/Network unavailable/);assert.equal(button.disabled,false);
 console.log('Worker detail rendering and cash verification tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
